//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 10:01:06 AM IST 
//


package com.ibm.betaworks;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmployeeResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployeeResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DBResp"/>
 *         &lt;element ref="{http://sample/iibadmin}EMPLOYEE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployeeResponseType", propOrder = {
    "dbResp",
    "employee"
})
public class EmployeeResponseType {

    @XmlElement(name = "DBResp", required = true)
    protected DBRespType dbResp;
    @XmlElement(name = "EMPLOYEE", namespace = "http://sample/iibadmin")
    protected List<EMPLOYEEType> employee;

    /**
     * Gets the value of the dbResp property.
     * 
     * @return
     *     possible object is
     *     {@link DBRespType }
     *     
     */
    public DBRespType getDBResp() {
        return dbResp;
    }

    /**
     * Sets the value of the dbResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBRespType }
     *     
     */
    public void setDBResp(DBRespType value) {
        this.dbResp = value;
    }

    /**
     * Gets the value of the employee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMPLOYEE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EMPLOYEEType }
     * 
     * 
     */
    public List<EMPLOYEEType> getEMPLOYEE() {
        if (employee == null) {
            employee = new ArrayList<EMPLOYEEType>();
        }
        return this.employee;
    }

}
