//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 10:01:06 AM IST 
//


package com.ibm.betaworks;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.betaworks package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EmployeeResponse_QNAME = new QName("http://sample/iibadmin", "EmployeeResponse");
    private final static QName _DBResp_QNAME = new QName("", "DBResp");
    private final static QName _EMPLOYEE_QNAME = new QName("http://sample/iibadmin", "EMPLOYEE");
    private final static QName _EMPLOYEETypePHONENO_QNAME = new QName("", "PHONENO");
    private final static QName _EMPLOYEETypeWORKDEPT_QNAME = new QName("", "WORKDEPT");
    private final static QName _EMPLOYEETypeMIDINIT_QNAME = new QName("", "MIDINIT");
    private final static QName _EMPLOYEETypeSEX_QNAME = new QName("", "SEX");
    private final static QName _EMPLOYEETypeCOMM_QNAME = new QName("", "COMM");
    private final static QName _EMPLOYEETypeJOB_QNAME = new QName("", "JOB");
    private final static QName _EMPLOYEETypeBONUS_QNAME = new QName("", "BONUS");
    private final static QName _EMPLOYEETypeSALARY_QNAME = new QName("", "SALARY");
    private final static QName _EMPLOYEETypeBIRTHDATE_QNAME = new QName("", "BIRTHDATE");
    private final static QName _EMPLOYEETypeHIREDATE_QNAME = new QName("", "HIREDATE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.betaworks
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EMPLOYEEType }
     * 
     */
    public EMPLOYEEType createEMPLOYEEType() {
        return new EMPLOYEEType();
    }

    /**
     * Create an instance of {@link EmployeeResponseType }
     * 
     */
    public EmployeeResponseType createEmployeeResponseType() {
        return new EmployeeResponseType();
    }

    /**
     * Create an instance of {@link DBRespType }
     * 
     */
    public DBRespType createDBRespType() {
        return new DBRespType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sample/iibadmin", name = "EmployeeResponse")
    public JAXBElement<EmployeeResponseType> createEmployeeResponse(EmployeeResponseType value) {
        return new JAXBElement<EmployeeResponseType>(_EmployeeResponse_QNAME, EmployeeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DBRespType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DBResp")
    public JAXBElement<DBRespType> createDBResp(DBRespType value) {
        return new JAXBElement<DBRespType>(_DBResp_QNAME, DBRespType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EMPLOYEEType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sample/iibadmin", name = "EMPLOYEE")
    public JAXBElement<EMPLOYEEType> createEMPLOYEE(EMPLOYEEType value) {
        return new JAXBElement<EMPLOYEEType>(_EMPLOYEE_QNAME, EMPLOYEEType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PHONENO", scope = EMPLOYEEType.class)
    public JAXBElement<String> createEMPLOYEETypePHONENO(String value) {
        return new JAXBElement<String>(_EMPLOYEETypePHONENO_QNAME, String.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WORKDEPT", scope = EMPLOYEEType.class)
    public JAXBElement<String> createEMPLOYEETypeWORKDEPT(String value) {
        return new JAXBElement<String>(_EMPLOYEETypeWORKDEPT_QNAME, String.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIDINIT", scope = EMPLOYEEType.class)
    public JAXBElement<String> createEMPLOYEETypeMIDINIT(String value) {
        return new JAXBElement<String>(_EMPLOYEETypeMIDINIT_QNAME, String.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SEX", scope = EMPLOYEEType.class)
    public JAXBElement<String> createEMPLOYEETypeSEX(String value) {
        return new JAXBElement<String>(_EMPLOYEETypeSEX_QNAME, String.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMM", scope = EMPLOYEEType.class)
    public JAXBElement<BigDecimal> createEMPLOYEETypeCOMM(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_EMPLOYEETypeCOMM_QNAME, BigDecimal.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JOB", scope = EMPLOYEEType.class)
    public JAXBElement<String> createEMPLOYEETypeJOB(String value) {
        return new JAXBElement<String>(_EMPLOYEETypeJOB_QNAME, String.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BONUS", scope = EMPLOYEEType.class)
    public JAXBElement<BigDecimal> createEMPLOYEETypeBONUS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_EMPLOYEETypeBONUS_QNAME, BigDecimal.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SALARY", scope = EMPLOYEEType.class)
    public JAXBElement<BigDecimal> createEMPLOYEETypeSALARY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_EMPLOYEETypeSALARY_QNAME, BigDecimal.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BIRTHDATE", scope = EMPLOYEEType.class)
    public JAXBElement<XMLGregorianCalendar> createEMPLOYEETypeBIRTHDATE(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EMPLOYEETypeBIRTHDATE_QNAME, XMLGregorianCalendar.class, EMPLOYEEType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HIREDATE", scope = EMPLOYEEType.class)
    public JAXBElement<XMLGregorianCalendar> createEMPLOYEETypeHIREDATE(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EMPLOYEETypeHIREDATE_QNAME, XMLGregorianCalendar.class, EMPLOYEEType.class, value);
    }

}
